Upgrade React Router 5 -> 6
navikt/syfomodiaperson pull request #689
Opened 2022-05-10 12:16 UTC by andersrognstad

- Endret `<Redirect>` til `<Navigate>`
- Bruke `<Routes>` og `<Route element={..} />` i `AppRouter`
- Custom `withRouter`-wrapper for å støtte møteplanlegger-komponenter
- util for tester som bruker `MemoryRouter`

Ref https://reactrouter.com/docs/en/v6/upgrading/v5

2022-05-10 12:46 UTC, janzh approved these changes

2022-05-10 14:35 UTC, janzh requested changes
Ruter for IngenAktivBrukerRouter trenger å fikses.
IngenAktivBrukerRouter blir nå ikke visst, man får kun blank skjerm.

2022-05-11 06:06 UTC, andersrognstad commented
> Ruter for IngenAktivBrukerRouter trenger å fikses. IngenAktivBrukerRouter blir nå ikke visst, man får kun blank skjerm. Kan testes i dev ved f.eks å gå til Syfooversikt, åpne decorator og trykke på lenke til syfomodiaperson([Sykmeldt enkeltperson](https://syfomodiaperson.dev.intern.nav.no/sykefravaer/))

Ok, skal ta en titt!

2022-05-11 06:43 UTC, andersrognstad commented
> Ruter for IngenAktivBrukerRouter trenger å fikses. IngenAktivBrukerRouter blir nå ikke visst, man får kun blank skjerm. Kan testes i dev ved f.eks å gå til Syfooversikt, åpne decorator og trykke på lenke til syfomodiaperson([Sykmeldt enkeltperson](https://syfomodiaperson.dev.intern.nav.no/sykefravaer/))

Skal være fikset nå, fint om du tester.

2022-05-11 06:45 UTC, janzh approved these changes

2022-05-11 07:54 UTC, JMLindseth approved these changes

2022-05-11 08:12 UTC, merged